### ISSUE TITLE
Add --insecure option not to validate SSL certificates

### ISSUE THREAD

**Issue by olivergondza** [olivergondza/jenkins-config-cloner#2]
On a first look it seems that `hudson.cli.CLI` accepts `-noCertificateCheck` to do just that.

**Comment by akostadinov** [comment]
did this work?

**Comment by olivergondza** [comment]
I had to do https://github.com/olivergondza/jenkins-config-cloner/commit/718c7b38d38f1ee65bccf7203aaeacadb6c2284d first and then have no time to continue.

**Comment by olivergondza** [comment]
@akostadinov, please check the latest version: `./clone.sh job --insecure src_url dst_url`

**Comment by akostadinov** [comment]
updated instruction doc so hopefully people can try it out, can't test myself now but got a couple of people that should be migrating jobs, that's why I bumped the issue, thank you!
